# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  BuildConfiguration : 'Release'

pool:
  vmImage: 'vs2017-win2016'


steps:

- task: DotNetCoreInstaller@0
  displayName: 'Installing .NET Core SDK...'
  inputs:
    version: 3.0.100-preview5-011568


- task: PowerShell@2
  inputs:
    filePath: './build.ps1'