# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  BuildConfiguration : 'Release'

pool:
  vmImage: 'vs2017-win2016'


steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'mkdir repo  

            cd repo

            git config --global user.email "azuredevops@azure.com"

            git config --global user.name "DevOps"

            git clone https://github.com/detachmode/DotnetBlayer.git

            cd DotnetBlayer

            git checkout -b gh-pages

            git pull

            echo hi >> test.txt

            git add .

            git commit -m "test.txt"
            
            git push'

- task: DotNetCoreInstaller@0
  displayName: 'Installing .NET Core SDK...'
  inputs:
    version: 3.0.100-preview5-011568


- task: PowerShell@2
  inputs:
    filePath: './build.ps1'
