# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master



pool:
  vmImage: 'vs2017-win2016'


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: DotNetCoreInstaller@0
  displayName: 'Installing .NET Core SDK...'
  inputs:
    version: 3.0.100-preview-010184


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: CmdLine@2
  inputs:
    script: 'dir .'


- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Blayer.Contracts'
    feedsToUse: 'select'
    versioningScheme: 'off'


- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './ExampleApp/ExampleApp.csproj'
    feedsToUse: 'select'
    versioningScheme: 'off'
